# Generated by Django 2.1.5 on 2020-05-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200504_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], max_length=10),
        ),
    ]
