# Generated by Django 2.1.5 on 2020-05-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200508_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('invoice', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('records', models.ManyToManyField(to='inventory.Record')),
            ],
        ),
    ]
