# Generated by Django 2.1.5 on 2020-05-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='reference',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
