# Generated by Django 2.1.5 on 2020-05-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_bill_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('invoice', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=128)),
                ('customer', models.CharField(max_length=128)),
                ('reference', models.CharField(max_length=128, null=True)),
                ('records', models.ManyToManyField(to='inventory.Record')),
            ],
        ),
    ]
