# Generated by Django 2.1.5 on 2020-05-15 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.Product'),
            preserve_default=False,
        ),
    ]
